version: '3.7'

services:
  web:
    build:
      context: ./youdea
      dockerfile: Dockerfile
    command: gunicorn youdea.wsgi:application --bind 0.0.0.0:8000
    #volumes:
      #- static:/code/static
    expose:
      - 8000
    env_file: .env
    depends_on:
      - db
  db:
    image: postgres:11.2-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file: .env
  nginx:
    build: ./nginx
    #volumes:
      #- static:/code/static
    ports:
      - 8000:80
    depends_on:
      - web

volumes:
  postgres_data:
  #static:
